# Generated by Django 6.0.1 on 2026-01-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studymaterial_is_verified_studymaterial_uploaded_by'),
    ]

def merge_depts(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    DEPT_MAP = {
        'Computer Science & Engineering': 'Computer Science and Engineering',
        'Electronics & Communication': 'Electronics and Communication Engineering',
        'Electronics and Communication': 'Electronics and Communication Engineering',
        'Electronics & Communication Engineering': 'Electronics and Communication Engineering',
    }
    for old_name, new_name in DEPT_MAP.items():
        if old_name == new_name: continue
        # Find if both exist
        old_depts = Department.objects.filter(name=old_name)
        new_depts = Department.objects.filter(name=new_name)
        
        if old_depts.exists() and new_depts.exists():
            # In a real scenario, we'd move relationships here.
            # But since we're re-seeding everything anyway, we just delete the old one.
            old_depts.delete()
        elif old_depts.exists():
            # Rename if only old exists
            dept = old_depts.first()
            dept.name = new_name
            dept.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studymaterial_is_verified_studymaterial_uploaded_by'),
    ]

    operations = [
        migrations.RunPython(merge_depts),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
